INSERT INTO CAR(ID,IS_CREDITED,MARK,MODEL,YEAR,CREDIT_CAR_ID) VALUES(100, 0, 'SAAB', '9-3', 2007, null);
INSERT INTO CAR(ID,IS_CREDITED,MARK,MODEL,YEAR,CREDIT_CAR_ID) VALUES(101, 0, 'OPEL', 'VECTRA', 2004, null);
INSERT INTO CAR(ID,IS_CREDITED,MARK,MODEL,YEAR,CREDIT_CAR_ID) VALUES(102, 0, 'DACIA', 'LOGAN', 2017, null);